const SIGN_IN = "SIGN_IN" ; 
const GET_REQUESTED_TASKS = "GET_REQUESTED_TASKS" ;

const SINGLE_TASK = "SINGLE_TASK"  ; 

const LIST_DEPARTMENT = "LIST_DEPARTMENT";

const LIST_DEPARTMENT_GET_TASKS = "LIST_DEPARTMENT_GET_TASKS";

const LIST_ROLES = "LIST_ROLES" ;
const LIST_PROBLEMS = "LIST_PROBLEMS" ;

const LISTACCEPTEDTASKS ="LISTACCEPTEDTASKS" ;

const LISTCLOSEDTASKS = "LISTCLOSEDTASKS" ;

const LIST_WORKERS = "LIST_WORKERS" ;

const CREATE_USER = "CREATE_USER" ; 

const GET_TASKS = "GET_TASKS" ; 

const REQUEST_TASK = "REQUEST_TASK" ; 

const LOGGED_OUT = "LOGGED_OUT" ;

const LOGGED_IN = "LOGGED_IN" ;

const GET_CURRENT_USER = "GET_CURRENT_USER"

const LIST_ROOMS  = "LIST_ROOMS" ; 

const LIST_OPENED_TASKS  = "LIST_OPENED_TASKS" ;

const TASKCREATED  = "TASKCREATED" ; 

const LIST_USERS_SYSTEM = "LIDT_USERS_SYSTEM" ;



module.exports = {
    GET_TASKS,
    LIST_DEPARTMENT,
    REQUEST_TASK,
    SIGN_IN,
    LOGGED_OUT,
    LOGGED_IN,
    SINGLE_TASK,
    LIST_ROLES,
    CREATE_USER,
    LIST_DEPARTMENT_GET_TASKS,
    LIST_PROBLEMS,
    GET_REQUESTED_TASKS,
    LIST_WORKERS,
    LISTACCEPTEDTASKS,
    GET_CURRENT_USER,
    LISTCLOSEDTASKS,
    LIST_ROOMS,
    LIST_OPENED_TASKS,
    TASKCREATED,
    LIST_USERS_SYSTEM,
 } ; 